### PR TITLE
Fixed myImage Responsive Style

### PR DESCRIPTION
**Pull request by manishprivet**
Fixed responsiveness of myimage as it left a gap at bottom on mobile device.

### CODE REVIEW

**Comment by manishprivet** [comment]
@prmsrswt Please Approve

**Review by onprem — CHANGES_REQUESTED** [review]
Good work! Just some minor nits.

- We use 2 spaces instead of tabs in the whole codebase, can you please update your changes to use 2 spaces for indentation instead of tabs.
- We use `yarn` instead of `npm` for package management, and it is strongly advised to use only one of them in a project. So you need to delete the `package-lock.json` file form here as we already have the `yarn.lock` lockfile.

**Comment by manishprivet** [comment]
Changes have been done 😄

**Comment by onprem** [comment]
Great. Thanks!

**Pull request merged**
